"""news

Revision ID: 6b22af320fe4
Revises: fe6a8ffb4098
Create Date: 2025-05-22 15:10:18.717799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b22af320fe4'
down_revision: Union[str, None] = 'fe6a8ffb4098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.drop_column('users', 'emails')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emails', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
